### ISSUE TITLE
Cannot update plot state due to pickling error

### ISSUE THREAD

**Issue by worm00111** [fedden/poker_ai#63] opened 2020-04-13 12:17 UTC
**Describe the bug**
When trying to update the state of PokerPlot using the example provided in applications\visualisation\README.md the following error is returned:
`pluribus\games\short_deck\state.py", line 204, in _load_pickle_files      
    f"File path not found {file_path}. Ensure pickle_dir is "
ValueError: File path not found ../../research/blueprint_algo/preflop_lossless.pkl. Ensure pickle_dir is set to directory containing pickle files`

**To Reproduce**
1. Go to path 'scripts\test_hand.py' (which is using the example provided in applications\visualisation\README.md
2. Run command 'python test_hand.py'
3. See error

**Expected behavior**
PokerPlot state will be updated

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python version: Python 3.7.4
 - Browser Firefox

**Additional comments**
I thought it might be due to Windows using \\ to specify the path, but when I used "..\\\\..\\\\research\\\\blueprint_algo\\\\" path, I also got the same error

**Comment by fedden** [comment] 2020-04-13 12:20
Yeah so as it stands you don't have the pickle files that the state class needs. 

These can be produced by running the research code to produce the lossy abstractions, but you can also skip loading the pickle files in the state constructor by setting the below parameter to `False` on initialisation.

https://github.com/fedden/pluribus-poker-AI/blob/c6091b8be23257cd2b7c57a0f4b81749e7043ec3/pluribus/games/short_deck/state.py#L33

**Comment by fedden** [comment] 2020-04-13 12:20
If the pickle files aren't produced and uploaded, then you'll not be able to produce information sets, but you may not need to do this

**Comment by worm00111** [comment] 2020-04-13 12:24
Thanks for the quick reply! : )

**Comment by worm00111** [comment] 2020-04-13 12:49
Not that it reaches pp.update_state(state) without any errors, it doesn't look like it actually updates the state of the front end as the table still doesn't have any players around it, it's just a blank table.
![image](https://user-images.githubusercontent.com/15672591/79121503-62393b00-7d8d-11ea-84c5-d3f4ade8766e.png)

The state variable doesn't seem to be an issue as it has all the right properties:
![image](https://user-images.githubusercontent.com/15672591/79121601-93b20680-7d8d-11ea-8585-686afb720a6c.png)

Does the update_state(state) method work correctly for you?

**Comment by fedden** [comment] 2020-04-13 14:15
Yeah, so this is what I get when I run the first part of the script in my IPython shell on the right:
<img width="1680" alt="Screenshot 2020-04-13 at 15 13 23" src="https://user-images.githubusercontent.com/11923487/79127270-81d66080-7d99-11ea-8656-47a4821c2537.png">

Then, once I have added the following:
```python
state: ShortDeckPokerState = get_state()
pp.update_state(state)
```

It updates the visualisation to this:
<img width="1680" alt="Screenshot 2020-04-13 at 15 13 51" src="https://user-images.githubusercontent.com/11923487/79127310-9581c700-7d99-11ea-9b0d-87681bdb8b73.png">

**Comment by worm00111** [comment] 2020-04-13 15:15
The only differency that I have is that I disable the pickling of files
```
return ShortDeckPokerState(
        players=players, 
        load_pickle_files=False
    )
```
That seems to be the problem, so I tried generating the pickle files by running pluribus-poker-AI\research\blueprint_algo\blueprint_kuhn.py and pluribus-poker-AI\research\blueprint_algo\blueprint_short_deck_poker.py

blueprint_kuhn.py runs fine, but when I try to run blueprint_short_deck_poker.py I get a similar pickle error:
`train iter:   0%|                                                                       | 0/20000 [00:00<?, ?it/s] 
Traceback (most recent call last):
  File "c:\Users\Vilius\OneDrive\workarea\programming\2020\Python\pluribus-poker-AI\research\blueprint_algo\blueprint_short_deck_poker.py", line 421, in <module>
    train()
  File "C:\Users\Vilius\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Vilius\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 717, in main 
    rv = self.invoke(ctx)
  File "C:\Users\Vilius\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Vilius\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\Users\Vilius\OneDrive\workarea\programming\2020\Python\pluribus-poker-AI\research\blueprint_algo\blueprint_short_deck_poker.py", line 376, in train
    state: ShortDeckPokerState = new_game(n_players, info_set_lut)
  File "c:\Users\Vilius\OneDrive\workarea\programming\2020\Python\pluribus-poker-AI\research\blueprint_algo\blueprint_short_deck_poker.py", line 310, in new_game
    state = ShortDeckPokerState(players=players)
  File "C:\Users\Vilius\AppData\Local\Programs\Python\Python37\lib\site-packages\pluribus\games\short_deck\state.py", line 43, in __init__
    self.info_set_lut = self._load_pickle_files(pickle_dir)
  File "C:\Users\Vilius\AppData\Local\Programs\Python\Python37\lib\site-packages\pluribus\games\short_deck\state.py", line 204, in _load_pickle_files
    f"File path not found {file_path}. Ensure pickle_dir is "
ValueError: File path not found .\preflop_lossless.pkl. Ensure pickle_dir is set to directory containing pickle files`

I noticed that a pickle file pluribus-poker-AI\research\clustering\data\preflop_lossless.pkl so I tried moving that into pluribus-poker-AI\research\blueprint_algo\ folder but I still get the same error

**Comment by fedden** [comment] 2020-04-13 16:06
That's not how to produce the pickle files you'll need. 

That work is in the abstraction section of the research directory. At the moment we aren't supporting anything we leave in the [research/](https://github.com/fedden/pluribus-poker-AI/tree/develop/research) directory - this is our directory for hacking together ideas, and once they ready, we'll add them to the [pluribus/](https://github.com/fedden/pluribus-poker-AI/tree/develop/pluribus) directory

**Comment by fedden** [comment] 2020-04-13 16:08
Feel free to run the scripts [here](https://github.com/fedden/pluribus-poker-AI/tree/develop/research/clustering)

**Comment by fedden** [comment] 2020-04-13 16:09
But we can't really support this until it becomes an official part of the project (i.e until we are confident it works)

**Comment by fedden** [comment] 2020-04-13 16:10
For the visualisation code, which again is very much a work in progress, you can initialise the state without the pickle files, in the way that you already have, and then there must be some other issue that is causing you not to have the players appear in the visualisation

**Comment by fedden** [comment] 2020-04-13 16:15
If you can find the specific problem on your system that is preventing you from visualising the players I'd be very amenable to fixing it, but at the moment the visualisation is very much WIP so you'll need to debug it yourself as I can't replicate your problem as demonstrated here: https://github.com/fedden/pluribus-poker-AI/issues/63#issuecomment-612916394

**Comment by fedden** [comment] 2020-04-13 16:16
Gonna close this until there is a more specific problem to fix!

**Comment by fedden** [comment] 2020-04-13 16:17
(I also can't support Windows as I am a Linux/OS X user and don't have a Windows machine to test the software on)

**Comment by worm00111** [comment] 2020-04-14 09:23
That;s understandable, thanks for the response. When you have the time, would you be able to run update_state with load_pickle_files=False just so I know whether it's due to pickle files or something specific to my setup

**Comment by fedden** [comment] 2020-04-14 09:25
Sure thing @worm00111 , in the interests of reproducability, could you paste here the complete script you are calling, so I can call that without any questions of difference?

**Comment by worm00111** [comment] 2020-04-14 09:30
from plot import PokerPlot
from pluribus.games.short_deck.player import ShortDeckPokerPlayer
from pluribus.games.short_deck.state import ShortDeckPokerState
from pluribus.poker.pot import Pot


def get_state() -> ShortDeckPokerState:
    """Gets a state to visualise"""
    n_players = 6
    pot = Pot()
    players = [
        ShortDeckPokerPlayer(player_i=player_i, initial_chips=10000, pot=pot)
        for player_i in range(n_players)
    ]
    return ShortDeckPokerState(
        players=players,
        load_pickle_files=False
    )


pp: PokerPlot = PokerPlot()
state: ShortDeckPokerState = get_state()
pp.update_state(state)

**Comment by worm00111** [comment] 2020-04-14 09:30
Sorry, for the formatting, can't seem to enclose the entire thing in a code block

**Comment by fedden** [comment] 2020-04-14 09:31
can you reformat it using backticks so it has the correct format?
It should look like this:
    ```python
    ```

**Comment by fedden** [comment] 2020-04-14 09:32
If you can format it as here that would be helpful to be sure I am running the same code as ou are! https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks

**Comment by worm00111** [comment] 2020-04-14 09:34
Cheers, updated the message.

**Comment by fedden** [comment] 2020-04-14 10:07
Okay great, I can confirm I can replicate the issue. For now the (disgusting/hacky) fix is to insert a lengthly sleep inbetween the call like so:
```python
import time

from plot import PokerPlot
from pluribus.games.short_deck.player import ShortDeckPokerPlayer
from pluribus.games.short_deck.state import ShortDeckPokerState
from pluribus.poker.pot import Pot


def get_state() -> ShortDeckPokerState:
    """Gets a state to visualise"""
    n_players = 6
    pot = Pot()
    players = [
        ShortDeckPokerPlayer(player_i=player_i, initial_chips=10000, pot=pot)
        for player_i in range(n_players)
    ]
    return ShortDeckPokerState(players=players, load_pickle_files=False)


pp: PokerPlot = PokerPlot()
state: ShortDeckPokerState = get_state()
time.sleep(5)
print("updating state")
pp.update_state(state)
```

**Comment by fedden** [comment] 2020-04-14 10:07
I'll try to dig into this (when I can) and will make sure this works in the future

**Comment by fedden** [comment] 2020-04-14 10:12
The reason why I hadn't discovered this previously was because I was running this code in one IPython cell:
```python
import time

from plot import PokerPlot
from pluribus.games.short_deck.player import ShortDeckPokerPlayer
from pluribus.games.short_deck.state import ShortDeckPokerState
from pluribus.poker.pot import Pot


def get_state() -> ShortDeckPokerState:
    """Gets a state to visualise"""
    n_players = 6
    pot = Pot()
    players = [
        ShortDeckPokerPlayer(player_i=player_i, initial_chips=10000, pot=pot)
        for player_i in range(n_players)
    ]
    return ShortDeckPokerState(players=players, load_pickle_files=False)


pp: PokerPlot = PokerPlot()
```

And this in a second IPython cell:
```python
state: ShortDeckPokerState = get_state()
pp.update_state(state)
```

And there was a considerable time-gap in between the execution of the cells!

**Comment by worm00111** [comment] 2020-04-14 10:24
Woop woop! It's good to know that there's a way to get around this : )

**Closed** 2020-07-05 14:12 UTC
Labels: bug
